### ISSUE TITLE
Question: Are database lookups done in parallel?

### ISSUE THREAD

**Issue by digitalronin** [mneudert/geolix#5]
Hi there

Thanks for this great library.

I have a system where I need to get the result of looking up an IP in several maxmind databases; country, isp, connection type and anonymous proxy. I was planning to kick off lookups using Task.async, but I'm not sure if that would have any benefit.

Does geolix lookup each registered database concurrently, or in series?

David

**Comment by mneudert** [comment]
Currently all lookups are done in series in `Geolix.Database.lookup/2`.

But as you mention it it should be a good thing to support a concurrent lookup out of the box. The parsed database contents are already stored in agents, so it should not be that much work. And if their workload gets too high the storage could be changed to an ets table or something different. Depending on what happens when the lookup is changed.

For the time being your best approach might be passing a specific database to lookup using `Geolix.lookup("127.0.0.1", where: :city)` and handle the concurrency yourself. With a raised pool size it should at least work.

Would be great to get some numbers on that ;)

**Comment by mneudert** [comment]
Well, partially ignore what I said.

I just looked into what it would take to change the lookup and while the change was as small as expected the gain was quite nice. Using just the city and the country database the time taken went down to what seemed just above half the time.

Hope you can give the changed lookup a try.

If it performs well I would release a new version to hex asap.

**Comment by digitalronin** [comment]
Wow, that was fast!

Thanks so much for doing this. I'll check it out today, and see how it compares.

David

**Comment by digitalronin** [comment]
Just FYI, here are some unscientific results;

Using a long list (around 280k IPs), my original code (Calling Geolix.lookup(str) using Task.async to do two lookups - country & ISP) took around 100 seconds to process the list.

Scoping each lookup using 'where: :country' and 'where: :isp' took this down to around 75 seconds.

Using the latest version of the code, where you're doing the Task.async part, and replacing my two Task.async calls with a single, Geolix.lookup(str) drops that down to around 60 seconds.

I'd call that a pretty good result, although this definitely isn't a rigorous benchmark.

Thanks again for the library, and for making this change so quickly.

David
